### ISSUE TITLE
Java 8 and asciidoclet

### ISSUE THREAD

**Issue by Vad1mo** [asciidoctor/asciidoclet#18]
Hello, 
Doclint in jdk 8 is very strict. Switching it of is also not a really good idea. 

So the question is:
1. Is java 8 supported?
2. I have this entry in my javadoc. According to the asciidoctor docs I don't need to escape the special chracters but javadoc is complaining about the special characters. So who is right here?

``` java
/** 
* *Example:*
* [source,xml] 
* --
*                  <executions>
                    <execution>
                        <id>doIt</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
**/ --
```

**Comment by gjoseph** [comment]
In one of our project, when using the default doclet, we get a bunch of doclint failures, mostly for stuff that's indeed erroneous. When using asciidoclet, we get warnings instead. We don't get the warnings for, say, erroneous html, but we do get them for erroneous @see tags, for example. Is there any way we could control this behavior, i.e have it fail instead of just warn ? Is Javadoc's doclint somewhat reusable for other doclets (does that even make sense ?)
I tried -Xdoclint:all but I guess Asciidoclet would need to take into account for it to do anything.

ref: http://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#BEJEFABE
